name: 'Deploy UCD aapplication'
description: 'Run UCD Application Process Request '
inputs:
  application:
    description: 'Application Name'
    required: true
  applicationProcess:
    description: 'Application Process Name'
    required: true
  environment:
    description: 'Environment Name'
    required: true
  onlyChanged:
    description: 'onlyChanged'
    required: false
    type: boolean
    default: false
  properties:
    description : 'Properties for Application process properties as a JSON String'
    required: false
    type: String
  propertiesfile:
    description : 'Properties file path in the repository for Application process properties'
    required: false
    type: String
  snapshot:
    description: 'Name/ID of the snapshot. Mutually exclusive with versions parameter'
    reqiuired: false
    type: String
  versions:
    description: 'Version along with component as a JSON string eg:- {\"version\":\"version1\" , \n  \"component\":\"component1\"} '
    required: false
    type: String
  hostname:
    description: 'UCD hostname'
    required: true
  port:
    description: 'port'
    required: true
    default: '8443'
  username:
    description: 'username'
    required: true
  password:
    description: 'password'
    required: false
    secret: true
  authToken:
    description: 'UCD auth token'
    required: false
    secret: true
  disableSSLVerification:
    description: 'skip SSL certificate validation when making HTTPS requests and this is discouraged'
    required: true
    type: boolean
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
